### GET ALL POSTS
GET http://docker.local:5050/api/posts HTTP/1.1

### GET A POST ? public
GET http://docker.local:5050/api/posts/4 HTTP/1.1

### ADD A POST ? public
POST http://docker.local:5050/api/posts/new HTTP/1.1
content-type: application/json

{
  "title": "New post title",
  "body": "New post body"
}

### UPDATE A POST ? public
PUT http://docker.local:5050/api/posts/edit/2 HTTP/1.1
content-type: application/json

{
  "title": "Updated title",
  "body": "Updated body"
}

### DELETE A POST ? public
DELETE http://docker.local:5050/api/posts/3 HTTP/1.1